export enum RouteEnums {
    LOGIN_SCREEN = 'LOGIN_SCREEN',
    SIGNUP_SCREEN = 'SIGNUP_SCREEN',
    CREDENTIAL_LISTING_SCREEN = 'CREDENTIAL_LISTING_SCREEN',
    FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN',
}